spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///mybatisplus
      username: root
      password: 123456789
# 开启mp的日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_ #全局配置
      logic-delete-field: flag #逻辑删除字段
      logic-delete-value: 1 #逻辑删除后对应的值
      logic-not-delete-value: 0 #逻辑删除前的值